using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Projeto_RH.Enums
{
    public enum Filial
    {
        Aracaju,
        Bauru,
        Birigui,
        Blumenau,
        Bom_Jesus_da_Lapa,
        Cachoeiro_de_Itapemirim,
        Campinas,
        Campos_dos_Goytacazes,
        Caxias_do_Sul,
        Colatina,
        Conselheiro_Lafaiete,
        Contagem,
        Curitiba,
        Divinópolis,
        Extrema,
        Feira_de_Santana,
        Florianópolis,
        Fortaleza,
        Franca,
        Governador_Valadares,
        Guarulhos,
        Ipatinga,
        Itabirito,
        Itaboraí,
        Itabuna,
        João_Monlevade,
        Joinville,
        Juazeiro_do_Norte,
        Juiz_de_Fora,
        Londrina,
        Manhuaçu,
        Montes_Claros,
        Nova_Serrana,
        Novo_Hamburgo,
        Passos,
        Patos_de_Minas,
        Petrolina,
        Pouso_Alegre,
        Presidente_Prudente,
        Ribeirão_Preto,
        Rio_de_Janeiro,
        Salvador,
        Santo_Antonio_de_Jesus,
        São_José_do_Rio_Preto,
        São_José_dos_Campos,
        Sao_Paulo,
        São_Paulo,
        Senhor_do_Bonfim,
        Sete_Lagoas,
        Teófilo_Otoni,
        Uberaba,
        Uberlândia,
        Varginha,
        Viana,
        Vitória_da_Conquista,
        Matriz
    }
}
